2024-10-03 14:27:35.443 +03:00 [INF] User profile is available. Using 'C:\Users\kira1\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2024-10-03 14:27:35.564 +03:00 [INF] Now listening on: https://localhost:7001
2024-10-03 14:27:35.564 +03:00 [INF] Now listening on: http://localhost:5001
2024-10-03 14:27:35.566 +03:00 [INF] Application started. Press Ctrl+C to shut down.
2024-10-03 14:27:35.566 +03:00 [INF] Hosting environment: Development
2024-10-03 14:27:35.567 +03:00 [INF] Content root path: C:\BSUIR_Labs\SPPR\Lab10\WEB_253504_Frolenko\WEB_253504_Frolenko.UI
2024-10-03 14:27:40.870 +03:00 [INF] Request starting HTTP/2 GET https://localhost:7001/ - null null
2024-10-03 14:27:40.905 +03:00 [INF] Executing endpoint 'WEB_253504_Frolenko.UI.Controllers.HomeController.Index (WEB_253504_Frolenko.UI)'
2024-10-03 14:27:40.918 +03:00 [INF] Route matched with {action = "Index", controller = "Home", page = "", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Index() on controller WEB_253504_Frolenko.UI.Controllers.HomeController (WEB_253504_Frolenko.UI).
2024-10-03 14:27:40.953 +03:00 [INF] Executed action WEB_253504_Frolenko.UI.Controllers.HomeController.Index (WEB_253504_Frolenko.UI) in 30.6212ms
2024-10-03 14:27:40.957 +03:00 [INF] Executed endpoint 'WEB_253504_Frolenko.UI.Controllers.HomeController.Index (WEB_253504_Frolenko.UI)'
2024-10-03 14:27:40.958 +03:00 [ERR] Ошибка при обработке запроса /
System.Exception: Тестовое исключение для проверки логирования
   at WEB_253504_Frolenko.UI.Controllers.HomeController.Index() in C:\BSUIR_Labs\SPPR\Lab10\WEB_253504_Frolenko\WEB_253504_Frolenko.UI\Controllers\HomeController.cs:line 27
   at lambda_method1(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WEB_253504_Frolenko.UI.Middleware.ExceptionLoggingMiddleware.Invoke(HttpContext context) in C:\BSUIR_Labs\SPPR\Lab10\WEB_253504_Frolenko\WEB_253504_Frolenko.UI\Middleware\ExceptionLoggingMiddleware.cs:line 22
2024-10-03 14:27:40.975 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Тестовое исключение для проверки логирования
   at WEB_253504_Frolenko.UI.Controllers.HomeController.Index() in C:\BSUIR_Labs\SPPR\Lab10\WEB_253504_Frolenko\WEB_253504_Frolenko.UI\Controllers\HomeController.cs:line 27
   at lambda_method1(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WEB_253504_Frolenko.UI.Middleware.ExceptionLoggingMiddleware.Invoke(HttpContext context) in C:\BSUIR_Labs\SPPR\Lab10\WEB_253504_Frolenko\WEB_253504_Frolenko.UI\Middleware\ExceptionLoggingMiddleware.cs:line 22
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-10-03 14:27:41.001 +03:00 [INF] Request finished HTTP/2 GET https://localhost:7001/ - 500 null text/html; charset=utf-8 132.7023ms
2024-10-03 14:28:02.194 +03:00 [INF] Request starting HTTP/2 GET https://localhost:7001/Product - null null
2024-10-03 14:28:02.198 +03:00 [INF] ---> request /Product returns 404
2024-10-03 14:28:02.200 +03:00 [INF] Request finished HTTP/2 GET https://localhost:7001/Product - 404 null text/plain 5.9429ms
2024-10-03 14:28:02.202 +03:00 [INF] Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:7001/Product, Response status code: 404
2024-10-03 14:28:24.351 +03:00 [INF] Application is shutting down...
